# Spring properties
spring:
  application:
     name: alerts-service
  freemarker:
      enabled: false

# HTTP Server
server:
  port: 8081   # HTTP (Tomcat) port

management:
  security:
    enabled: false

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
    instance:
        leaseRenewalIntervalInSeconds: 5
